#!/usr/bin/env python

from requests import get
from hashlib import md5

from os.path import exists
from sys import argv

def crackHash(h):
	r = get('http://google.com/search?q=%s' % h).content
	
	try: useful = r[r.index('<ol>'):r.index('</ol>')]
	except ValueError: useful = r
	
	for e in useful.split(' '):
		m = md5()
		m.update(e.encode('utf-8'))
	
		if m.hexdigest() == h:
			print '%s: %s' % (h, e)
			exit(0)
	
	print 'Couldn\'t find value for hash %s' % h
	
if (len(argv)-1)<1:
	print 'Usage: bzc <hash / file>'
	exit(1)

if exists(argv[1]):
	for e in open(argv[1]).read().split('\n'):
		crackHash(e)
		
else:
	crackHash(argv[1])
